site:
  production_url: "http://osx.gelistiriciyiz.biz"
  title: "OSX Püf Noktaları"
  subtitle: "OSX ile ilgili Türkçe püf noktaları"
  tag_line: "OSX İpuçları"
  description: "OSX ile ilgili Türkçe püf noktaları"
  logo: "logo.png"
  cover_image: "cover.jpg"
  social:
    twitter: "osx_tips_tr"
    facebook: "osxtips"
    google_analytics: "UA-6463685-43"
    disqus: "osxtipsgelistiriciyizbiz"
  company:
    name: "Geliştiriciyiz.biz"
    url: "http://gelistiriciyiz.biz/"
  product:
    name: "GELİŞTİRİCİYİZ.BİZ"
    url: "http://gelistiriciyiz.biz/"
  main_author:
    name: "Full Name"
    email: "email@example.com"
    link: "http://example.com"
    bio: "Title"